[package]
name = "wasteland-invaders"
version = "0.1.0"
edition = "2024"
authors = ["andrzej.witkowski@gmail.com"]
description = "A game built with the Bevy engine where players defend against invaders in a post-apocalyptic wasteland."
license = "MIT"
repository = "https://github.com/andrzejwitkowski/wasteland-invaders"

[dependencies]
bevy = "0.15.3"
bevy-inspector-egui = "0.30.0"
bevy_editor_pls = "0.10.0"
rand = "0.9.0"

[[bin]]
name = "wasteland-invaders"
path = "src/main.rs"
