name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (pkg-config, libudev, ALSA)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libudev-dev \
            libasound2-dev

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
